=== IperStan/mvc/mvc/mvc.dtd
<?xml version = "1.0"?>
<!--
/**
  *
  *
  *    Copyright 2015 - Cargopoooling, Inc. - U.S.A.
  *    Author: Cristian Costantini
  *    www.cargopooling.com
  *
  *    Licensed under the Apache License, Version 2.0 (the "License");
  *    you may not use this file except in compliance with the License.
  *    You may obtain a copy of the License at
  *
  *    http://www.apache.org/licenses/LICENSE-2.0
  *
  *    Unless required by applicable law or agreed to in writing, software
  *    distributed under the License is distributed on an "AS IS" BASIS,
  *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  *    See the License for the specific language governing permissions and
  *    limitations under the License.
  *
  *
**/
-->

<!ELEMENT modelglue (controllers, event-handlers, event-types, include)>

<!ELEMENT include ( value )>
<!ATTLIST include config CDATA >


<!ELEMENT controllers (controller)>

<!ELEMENT controller (event-listener)>

<!ATTLIST controller name CDATA #REQUIRED>
<!ATTLIST controller type CDATA #REQUIRED>

<!ELEMENT event-listener EMPTY>
<!ATTLIST event-listener message CDATA #REQUIRED>
<!ATTLIST event-listener function CDATA #REQUIRED>

<!ELEMENT event-handlers (event-handler)>

<!ELEMENT event-handler ( broadcasts, views, results )>

<!ATTLIST event-handler name CDATA #REQUIRED>
<!ATTLIST event-handler access (public|private) "public">
<!ATTLIST event-handler cache (true|false) "false">
<!ATTLIST event-handler cacheKey CDATA>
<!ATTLIST event-handler cachetimeout CDATA>
<!ATTLIST event-handler type CDATA>
<!ATTLIST event-handler contentType CDATA>
<!ATTLIST event-handler rest (true|false) "false">
<!ATTLIST event-handler method (GET|POST|PUT|DELETE) "false">


<!ELEMENT aliases ( alias )>

<!ELEMENT alias EMPTY>
<!ATTLIST alias name CDATA>
<!ATTLIST alias language CDATA>

<!ELEMENT broadcasts ( message )>

<!ELEMENT message ( argument )>
<!ATTLIST message name CDATA>

<!ELEMENT argument EMPTY>
<!ATTLIST argument name CDATA>
<!ATTLIST argument value CDATA>

<!ELEMENT views ( include )>


<!ATTLIST include name CDATA>
<!ATTLIST include template CDATA>
<!ATTLIST include conflict (append|prepend|overwrite) "overwrite">
<!ATTLIST include cache (true|false) "false">
<!ATTLIST include cacheKey CDATA>
<!ATTLIST include cachetimeout CDATA>

<!ELEMENT value EMPTY>
<!ATTLIST value name CDATA>
<!ATTLIST value value CDATA>

<!ELEMENT results ( result )>

<!ELEMENT result EMPTY>
<!ATTLIST result name CDATA>
<!ATTLIST result do CDATA>
<!ATTLIST result redirect (true|false) "false">
<!ATTLIST result append CDATA>
<!ATTLIST result statuscode (301|302|303) "302">


<!ELEMENT event-types (event-type)>

<!ELEMENT event-type (before,after)>
<!ATTLIST event-type name CDATA>

<!ELEMENT before (broadcasts,views,results)>
<!ELEMENT after (broadcasts,views,results)>

=== IperStan/mvc/examples/helloworldmg/config/ModelGlue.xml
<!DOCTYPE modelglue PUBLIC "-//MODELGLUE//DTD MODELGLUE//EN"
        "http://mm-projects.s3.amazonaws.com/dtd/mvc.dtd">
<modelglue>

	<controllers>

        <controller name="controller" type="examples.helloworldmg.controller.Controller">

            <event-listener message="sayHello" function="sayHello"/>

        </controller>

	</controllers>

	<event-handlers>

		<event-handler name="home" access="public">

			<views>
				<include name="body" template="body.cfm" />
			</views>

			<results>
				<result do="main"/>
			</results>

		</event-handler>

		<event-handler name="say.hello" access="public">

            <broadcasts>
                <message name="sayHello"/>
            </broadcasts>

			<results>
				<result do="home" redirect="false"/>
			</results>

		</event-handler>

		<event-handler name="exception" access="public">

            <views>
                <include name="body" template="exception.cfm" />
            </views>

			<results>
				<result do="main"/>
			</results>

		</event-handler>

		<event-handler name="not-found" access="public">

            <views>
                <include name="body" template="not-found.cfm" />
            </views>

			<results>
				<result do="main"/>
			</results>

		</event-handler>

        <event-handler name="main" access="private">

			<views>
				<include name="main" template="main.cfm" />
			</views>

		</event-handler>
		
	</event-handlers>
	
</modelglue>
